### ISSUE TITLE
output_transformer: test if transformer code works with more than one types (e.g. GESM, GESW)

### ISSUE THREAD

**Issue by bh1109** [CorrelAid/datenguide-python#22]

**Comment by KonradUdoHannes** [comment]
@bh1109 can you clarify what is meant? Do you mean fields returning enums that allow for several distinct values, or do you mean statistics returning several distinct enum fields or something entirely different?

**Comment by KonradUdoHannes** [comment]
Issue will be closed due to lack of a concrete description. Should a similar problem occur for anybody else please open up another issue.
