### ISSUE TITLE
list of arguments not possible in Query (as it is in datenguide API)

### ISSUE THREAD

**Issue by AlexandraKapp** [CorrelAid/datenguide-python#51]
Query.add_field('BEV001').add_args({'year':[2015, 2016]})

should be possible (with multiple years as list)

**Comment by KonradUdoHannes** [comment]
I thought we could already do it. This should have high priority in my opinion.

**Comment by AlexandraKapp** [comment]
actually, never mind. It is possible 😅 I just had an example where there was only values for one year...
