### ISSUE TITLE
update use-case "car accidents" to have more comments and examples

### ISSUE THREAD

**Issue by AlexandraKapp** [CorrelAid/datenguide-python#61]
expand car accident example as good "intro" notebook, to have an example for others to use

**Comment by elekt** [comment]
to get a bit into the repo I started to work on this issue
https://github.com/CorrelAid/datenguide-python/tree/61-updating-car-accidents

**Comment by KonradUdoHannes** [comment]
I think it is a good intro notebook, so I'll close the issue. I believe a good followup would be however to have dedicated requirements.txt files for the requirements associated with use cases, which are not associated with the package itself. This might help users that don't have so much experience setting up jupyter extensions, which can be a bit tricky as it is a multi step process.
