### ISSUE TITLE
add optional translation of descriptions in get_statistics

### ISSUE THREAD

**Issue by cbocionek** [CorrelAid/datenguide-python#69]
Add optional parameter to [get_statistics](https://github.com/CorrelAid/datenguide-python/blob/2f764c0a56500a95bf1829684ad96cdcae571037/datenguidepy/query_helper.py#L139) to specify in which language to return the short and long description of a statistic. Default will be German.

**Comment by enryH** [comment]
Could be done using [googletrans](https://pypi.org/project/googletrans/) for translating German to English:

```python
from googletrans import Translator
translator = Translator()

t = translator.translate('Regional Daten sind super spannend.', src='auto')
print(t.text)
t = translator.translate('Regional Daten sind super spannend.', src='de')
print(t.text)
## out
>>> Regional data are really exciting.
>>> Regional data are really exciting.
```

**Comment by cbocionek** [comment]
English translations of statistic descriptions can now be accessed via optional parameter `target_language`, i.e. `get_statistics(target_language='en')`.
By default, this uses a static translation file. Alternatively, an instance of an implementation of `TranslationProvider` can be passed to the method to translate the statistic descriptions on-the-fly.
